---
# tasks file for zabbix-agent-chocolatey
- name: Install zabbix-agent
  win_chocolatey:
    name: 
        - zabbix-agent
    state: present

- name: copy template zabbix agent
  win_template:
    src: zabbix_agentd.conf
    dest: 'C:\ProgramData\zabbix'

- name: Restart a service
  win_service:
    name: Zabbix Agent
    state: restarted    
