---
# tasks file for zabbix-agent
- name: Download zabbix agent
  win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/5.4/5.4.8/zabbix_agent-5.4.8-windows-amd64-openssl.msi
    dest: C:\Users\Administrator\Downloads\zabbix_agent.msi


- name: install zabbix agent
  win_command: msiexec /u "C:\Users\Administrator\Downloads\zabbix_agent.msi" /qn SERVER="{{ zabbix_server }}"

- name: copy template zabbix agent
  win_template:
    src: zabbix_agentd.conf
    dest: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'

- name: Restart a service
  win_service:
    name: Zabbix Agent
    state: restarted    
